research_task:
  description: >
    Generate a list of 1 interesting ideas for an blog post that didn't exist in our website apolline.art, then write one captivating title and paragraph to showcases the potential of a full article on this topic. Return this idea with the paraphagre and title
  expected_output: >
    A list with 1 bullet points of the most relevant information about
  agent: researcher_agent

keyword_task:
  description: >
    Generate a list of keywords for a given blog post, that are in the same thematique and should be include for the SEO optimization
  expected_output: >
    A list of keyword separated by coma of the most relevant keyword
  agent: keyword_agent

writter_task:
  description: >
    Generate a blog post in english and translated in french, using from the research agent and including the most relevant keywords in it, this article should be a perfect SEO blog post, with a good title, good amount of paragraph, and good amount of keyword
  expected_output: >
    An html file with the blog post, with the two language in it
  agent: seo_writter  
