idea_planner_task:
  description: >
    1. Research the topic "{topic}" using available data (e.g., Google search, competitor research, keyword tools).
    2. Compile a list of potential blog post ideas that would bring value to apolline.art’s audience.
    3. Provide a short explanation or rationale (1-2 sentences) for each idea, focusing on why it might be good for SEO and brand goals.
    4. Format the output as a Markdown report titled "Ideas Report."
    5. Ensure it is easy to read and only includes well-articulated ideas (no fluff).

  expected_output: >
    A clear, concise "Ideas Report" in Markdown, featuring multiple relevant blog topic suggestions with brief rationales.

  agent: idea_planner


planner_task:
  description: >
    1. Review the "Ideas Report" and select one "idea" that shows the highest potential for driving traffic and engagement.
    2. Conduct further research on the chosen idea. If needed, refine SEO keywords or supporting subtopics.
    3. Create a detailed content outline, specifying the blog structure (e.g., introduction, body sections, subheadings, conclusion).
    4. List at least 5-10 relevant keywords (including primary and secondary ones).
    5. Provide any additional resources or references that would help the writer (links, quotes, stats).
    6. Format the output as a Markdown report titled "Idea Plan."

  expected_output: >
    A comprehensive "Idea Plan" in Markdown with:
    - Selected topic
    - Keywords
    - Structured outline with potential headings
    - Helpful references/links

  agent: content_planner


write_task:
  description: >
    1. Using the "Idea Plan," write a final blog post of approximately 2,000 words.
    2. The structure should be in valid HTML:
       - A <h1> tag for the main title (required).
       - An introduction or hook below the title.
       - Body sections using <h2> for subsections.
       - A concluding paragraph with any call-to-action.
    3. Incorporate the keywords naturally, maintaining a factual, positive, and fun tone.
    4. Proofread for grammar, spelling, and clarity.
    5. Output the final content as a single HTML string, named "Final blog post", ready for publication on apolline.art.

  expected_output: >
    A complete HTML blog post (~2,000 words) with:
    - One <h1> tag for the main title
    - Several <h2> subsections
    - Properly formatted paragraphs
    - Overall consistency, SEO-friendly keywords, and a brand-aligned voice.

  agent: content_writer


publish_task:
  description: >
    Take the "Final blog post" generated by the content writer. The blog post is in HTML format and is guaranteed
    to have one <h1> tag for the main title at the start of the post.

    1. Locate the first <h1>...</h1> tag in the HTML and extract its inner text as the title.
       - If no <h1> tag is found (or it is empty), use "Untitled" as the fallback.
    2. Remove the entire <h1>...</h1> element from the HTML so it won't be duplicated in the body.
    3. Use the remaining HTML as the body.
    4. Call the "DrupalPublishTool" with the following arguments (in dictionary form):
       - "title": <the extracted or fallback title>
       - "body": <the remaining HTML after removing <h1> tag>
    5. Return the result of the tool call (confirmation message, node ID, etc.).

  expected_output: >
    A single string showing the "DrupalPublishTool" result, for example:
    "Successfully created new article. Node ID: abc123"
    or a descriptive error if publishing fails.

  agent: drupal_publisher
