idea_planner_task:
  description: >
    1. Exclude the {existing_articles} from this research
    2. Research the topic "{topic}" using available data (e.g., Google search, competitor research, keyword tools).
    3. Compile a list of 10 potential seo blog post ideas that would bring value for this {company} company in this {country} audience.
    4. Provide a short explanation or rationale (1-2 sentences) for each idea, focusing on why it might be good for SEO and brand goals.
    5. Ensure it is easy to read and only includes well-articulated ideas (no fluff).

  expected_output: >
    A clear, concise "Blog Post Ideas" in Markdown, featuring multiple relevant seo blog topic suggestions with brief rationales.

  agent: idea_planner


planner_task:
  description: >
    1. Review the "Blog Post Ideas" and select one form the list, that shows the highest potential for driving traffic and engagement.
    2. Conduct further research on the chosen idea. Refine SEO keywords or supporting subtopics based on actual search trends and musical theatre interest.
    4. Create a detailed content outline, specifying the blog structure (e.g., introduction, body sections, subheadings, conclusion).
    5. List at least 20-30 relevant SEO keywords, organized as:
      Primary Keywords:
        {topic} specific keyword the list here {topic_keyword}, you must include them
        Compagny specific keyword the list here {company_keyword} you must include them
      Secondary Keywords:
        {topic} keyowrd specific/long-tail
        Itent keywords that capture the exact intent of potential readers
    6. Provide any additional resources or references that would help the writer (links, quotes, stats, rankings, reviews, etc.).
    7. Format the output as a Markdown report titled "Idea Plan".
    8. Store the title of the blog post as "Post Title" and it should not be longuer than 60 characters

  expected_output: >
    A comprehensive "Idea Plan" in Markdown with:
    - Selected topic
    - Refined keywords including real {topic} names and search phrases
    - Structured outline with potential H2/H3 headings
    - Helpful references/links to support writing and SEO
    - Metadata suggestions (meta title and meta description)

  agent: content_planner


write_task:
  description: >
    1. Using the "Idea Plan," write a final blog post of approximately 2,000 words.
    2. The structure should be in valid HTML:
       - content sections using <h2> for subsections.
       - A concluding paragraph with any call-to-action.
    3. Incorporate the keywords naturally, maintaining a ton of voice {ton_of_voice}
    4. The primary keywords need to be included in the page 10-12 times, and the secondary keyword 2-3 times each, they have been listed by priority order first are more important
    5. Proofread for grammar, spelling, and clarity.
    6. Output the final content as a single HTML string, not an html page, but only the content section of the post
    7. Named this content "Final blog post", and keep the "Post title" ready for publication on {company}.
    8. Don't use complex words, it should be simple to read


  expected_output: >
    - First line the Title
    - Then the "Final blog post" a complete HTML blog post (~2,000 words) with:
    - Several <h2> subsections
    - Properly formatted paragraphs
    - Overall consistency, SEO-friendly keywords, and a brand-aligned voice.
    - Ready to be published, no dummy data, well finilized
  agent: content_writer


translater_task:
  description: >
    1. Take "Final blog post" and translate it into all those languages {language_list}, one by one.
    2. Your translation must be natural, fluent, and culturally adapted to each language — it must read like it was originally written by a native SEO copywriter.
    3. Preserve the structure and tags of the original HTML (e.g., <h2>, <p>, <ul>, <li>, <strong>, etc.) — do not remove or alter the structure, but tranlsate everything
    4. Carefully translate key SEO elements: titles, headings, keywords, lists, and emphasized terms. Maintain SEO integrity (including keyword usage, subheadings, and readability).
    5. Ensure that each translation maintain a tone of voice {ton_of_voice}.
    6. Proofread each version to eliminate spelling, grammar, or clarity issues. Final output must be publication-ready.
    7. For RTL (right-to-left) languages like Arabic or Hebrew, wrap the content in a <div dir="rtl"> ... </div>.

  expected_output: >
    XML strutured like this one, ready to be parsed with nothing else, do not forget the CDATA for the title and body
    <articles>
     <article code=\"en\">
      <title><![CDATA[Welcome Title ]]></title>
      <body><![CDATA[This is the English body]]></body>
     </article>
     <article code=\"es\">
      <title><![CDATA[Título de Bienvenida]]></title>
      <body><![CDATA[Este es el contenido en español]]>rr</body>
     <article>
    </articles>

  agent: translater_agent
